# Generated by Django 2.2.5 on 2019-10-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='subscriptionId',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='feed',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
