# Generated by Django 2.2.5 on 2019-10-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191012_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
