# Generated by Django 2.2.5 on 2019-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20191012_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='messageCategory',
            field=models.CharField(default='NONE', max_length=255),
            preserve_default=False,
        ),
    ]
