# Generated by Django 2.2.5 on 2019-10-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0002_auto_20190930_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='college',
            field=models.ForeignKey(db_column='college', on_delete=django.db.models.deletion.DO_NOTHING, related_name='drives', to='atnp.College'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atnp.Student'),
        ),
    ]
