# Generated by Django 2.2.5 on 2019-10-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0004_auto_20191002_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='isEditable',
            field=models.BooleanField(blank=True, db_column='isEditable', max_length=255, null=True),
        ),
    ]
