# Generated by Django 2.2.5 on 2019-10-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0005_auto_20191002_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resumes', to='atnp.Student'),
        ),
    ]
