# Generated by Django 2.2.5 on 2019-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0006_auto_20191002_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeopening',
            name='resumeUrl',
            field=models.CharField(blank=True, db_column='resumeUrl', max_length=255, null=True),
        ),
    ]
