# Generated by Django 2.2.5 on 2019-10-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0007_resumeopening_resumeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeopening',
            name='isEditable',
            field=models.BooleanField(blank=True, db_column='isEditable', max_length=255, null=True),
        ),
    ]
