# Generated by Django 2.2.5 on 2019-10-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0010_auto_20191002_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(db_column='company', on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='atnp.Company'),
        ),
    ]
