# Generated by Django 2.2.5 on 2019-10-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0011_auto_20191002_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyindrive',
            old_name='driveId',
            new_name='drive',
        ),
    ]
