# Generated by Django 2.2.5 on 2019-10-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0012_auto_20191002_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='round',
            field=models.ForeignKey(blank=True, db_column='round', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='atnp.Round'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='companyInDrive',
            field=models.ForeignKey(db_column='companyInDrive', on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobOpenings', to='atnp.CompanyInDrive'),
        ),
    ]
