# Generated by Django 2.2.5 on 2019-10-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0013_auto_20191005_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='resumeOpeningId',
            new_name='resumeOpening',
        ),
    ]
