# Generated by Django 2.2.5 on 2019-10-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0016_feed_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
