# Generated by Django 2.2.5 on 2019-10-09 06:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0020_auto_20191009_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeopening',
            name='proofs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.RemoveField(
            model_name='studentindrive',
            name='proofs',
        ),
        migrations.AddField(
            model_name='studentindrive',
            name='proofs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, db_column='proof', null=True), blank=True, default=list, null=True, size=None),
        )
    ]
