# Generated by Django 2.2.5 on 2019-10-12 19:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0022_auto_20191011_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeopening',
            name='commentJson',
        ),
        migrations.AddField(
            model_name='resumeopening',
            name='commentJson',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, db_column='commentJson', null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
