# Generated by Django 2.2.5 on 2019-10-14 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0024_auto_20191012_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='email', max_length=255)),
                ('message', models.EmailField(db_column='message', max_length=2000)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
