# Generated by Django 2.2.5 on 2019-10-16 06:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0026_auto_20191014_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyindrive',
            name='KYC',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, db_column='kyc', default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='drive',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, db_column='resources', default=list, null=True, size=None),
        ),
    ]
