# Generated by Django 2.2.5 on 2019-10-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0027_auto_20191016_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='category',
            field=models.CharField(db_column='category', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(db_column='message', max_length=2000),
        ),
    ]
