# Generated by Django 2.2.5 on 2019-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0028_auto_20191017_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentindrive',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
    ]
