# Generated by Django 2.2.5 on 2019-11-06 18:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0030_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumeopening',
            name='resumeJson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='resumeJson', default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='studentindrive',
            name='status',
            field=models.CharField(blank=True, default='pendingRegistration', max_length=255, null=True),
        )
    ]
