# Generated by Django 2.2.5 on 2019-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0031_auto_20191106_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentindrive',
            name='branch',
            field=models.CharField(blank=True, db_column='branch', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentindrive',
            name='cgpa',
            field=models.FloatField(blank=True, db_column='cgpa', max_length=255, null=True),
        ),
    ]
