# Generated by Django 2.2.5 on 2019-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atnp', '0032_auto_20191212_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentindrive',
            name='cgpa',
            field=models.FloatField(blank=True, db_column='cgpa', null=True),
        ),
    ]
